### ISSUE TITLE
k8s: all node types have the same (pod) icon

### ISSUE THREAD

**Issue by hunchback** [skydive-project/skydive-ui#2]
![image](https://user-images.githubusercontent.com/2760739/68541926-45e43d00-03ae-11ea-83d0-2156092c56e7.png)

**Comment by hunchback** [comment]
in the image you can see many types of nodes: cluster, namespace, pod all have the same icon (which is a parity from the legacy ui)

**Comment by safchain** [comment]
should be addressed by this : https://github.com/skydive-project/skydive-ui/commit/ec47044adb79429141f70770ad21463ce729d480

**Comment by hunchback** [comment]
still getting:

![image](https://user-images.githubusercontent.com/2760739/68672688-ccd61880-055a-11ea-8d36-160a62c0e8a6.png)

while code appears up to date:

![image](https://user-images.githubusercontent.com/2760739/68672721-deb7bb80-055a-11ea-8906-f4eeb5f77b39.png)

**Comment by safchain** [comment]
I see why, going to fix that

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68680488-66f18d00-056a-11ea-9ad7-bf3fa7f395bb.png)

**Comment by safchain** [comment]
should be fix: https://github.com/skydive-project/skydive-ui/commit/173aba57ddeb0842ba6870f00079fac1e132f85c

**Comment by hunchback** [comment]
![image](https://user-images.githubusercontent.com/2760739/68844213-1c8b2000-06d2-11ea-9173-18bb6c184994.png)

fixed!
